# work flow 의 이름
name: pull-request_build

on: 
  pull_request_target:
    types: [opened, reopened, synchronize, closed]

runs-on: macos-latest

jobs:
  job1:
     steps:
      - name: job1 - step1
        run: |
          echo "job1 - step1 -> exit 1"
          exit 1
      - name: job1 - step2
        run: |
          echo "job1 - step2 -> exit 1"
          exit 1
  job2:
    if: failure()
     steps:
      - name: job2 - step1
        run: |
          echo "job2 - step1 -> exit 1"
          exit 1
      - name: job2 - step2
        run: |
          echo "job2 - step2 -> exit 1"
          exit 1
  job3:
     steps:
      - name: job3 - step1
        run: |
          echo "job3 - step1 -> exit 65"
          exit 1
      - name: job3 - step2
        run: |
          echo "job2 - step2 -> exit 65"
          exit 1