# work flow 의 이름
name: pull-request_build


# 특정 pull-request 이벤트 발생 시 work flow 를 trigger
on: 
  pull_request_target:
    types: [opened, reopened, synchronize, closed]


# work flow를 구성하는 job 목록
jobs:
  # work flow를 구성하는 'set-up' job
  set-up:
    # job이 실행될 환경 - 최신 mac os
    runs-on: macos-latest
    # step은 job의 일부로 실행될 일련의 task들을 나타냄
    steps:
      - name: success test
        # 성공 스크립트 실행
        run: |
          echo "현재 디렉토리: $(pwd)"
          echo "프로젝트 디렉토리: ${GITHUB_WORKSPACE}"
          echo "스크립트 디렉토리 내부 파일: ${ls ${GITHUB_WORKSPACE}/scripts}"
          echo "Files in the workspace: $(ls ${GITHUB_WORKSPACE})"
